version: '3.8'
services:
  todo-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        VITE_BACKEND_URL: http://localhost:3000
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.js:/app/vite.config.js
      - ./package.json:/app/package.json
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
    command: npm run dev -- --host 0.0.0.0 